# Generated by Django 5.2 on 2025-04-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(choices=[(1, 'Batch 1'), (2, 'Batch 2'), (3, 'Batch 3')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('task_description', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
