# Generated by Django 5.2 on 2025-04-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='admin', max_length=10),
        ),
    ]
