# Generated by Django 5.2 on 2025-05-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
