# Generated by Django 5.2 on 2025-05-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0004_task_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='emotion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
